version: "3.8"

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432} # Default port is 5432 if not provided
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${PORT:-3001} # Default port is 3001 if not provided
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432} # Default port is 5432 if not provided
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    environment:
      REACT_APP_SERVER_PORT: ${PORT:-3001}
    ports:
      - "3000:3000"
    env_file:
      - .env
